/**
 * Classification accuracy eval — PRD acceptance criterion #5.
 *
 * Runs the `classify` node against all 25 hand-labeled fixture submissions and
 * asserts overall accuracy >= 80%. It also writes a fresh EVAL.md report.
 *
 * This makes 25 live LLM calls, so it is gated behind RUN_EVAL — a normal
 * `npm test` skips it instantly. Run it deliberately:
 *
 *   npm run eval
 *
 * Calls are paced (EVAL_DELAY_MS, default 7s) to stay under the Gemini free
 * tier's per-minute limit. A free-tier *daily* quota can still block a run —
 * if every result comes back `other` / confidence 0, you have hit the daily
 * cap; re-run on fresh quota or a funded key.
 */
import { describe, it, expect } from "vitest";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { classify } from "@/agent/nodes/classify";
import { activeModelId } from "@/agent/model";
import { TRIAGE_CATEGORIES, type RawSubmission } from "@/agent/schemas";
import type { TriageState } from "@/agent/state";
import fixturesData from "../fixtures/submissions.json";

interface Fixture {
  id: string;
  source: string;
  formType: string;
  submitterEmail?: string;
  submitterName?: string;
  priority: "normal" | "high";
  payload: { subject?: string; message?: string } & Record<string, unknown>;
  expectedCategory: string;
}

const fixtures = (fixturesData as { submissions: Fixture[] }).submissions;

function toRawSubmission(f: Fixture): RawSubmission {
  const body = [f.payload.subject, f.payload.message]
    .filter((v): v is string => typeof v === "string" && v.length > 0)
    .join("\n\n");
  return {
    submissionId: f.id,
    productSlug: f.source,
    formType: f.formType,
    submittedAt: new Date().toISOString(),
    body,
    contactEmail: f.submitterEmail,
    contactName: f.submitterName,
    priority: f.priority,
  };
}

function makeState(rawSubmission: RawSubmission): TriageState {
  return {
    rawSubmission,
    classification: undefined,
    enrichment: undefined,
    proposedAction: undefined,
    approval: undefined,
    execution: undefined,
  };
}

interface Result {
  id: string;
  expected: string;
  actual: string;
  confidence: number;
  correct: boolean;
}

const enabled =
  Boolean(process.env.RUN_EVAL) &&
  Boolean(process.env.GEMINI_API_KEY || process.env.ANTHROPIC_API_KEY);

describe.skipIf(!enabled)("classification accuracy eval", () => {
  it(
    "classifies the 25-fixture set with >= 80% accuracy",
    async () => {
      const results: Result[] = [];
      const delayMs = Number(process.env.EVAL_DELAY_MS ?? "7000");

      // Sequential + paced — kinder to rate limits than parallel fan-out.
      for (const fixture of fixtures) {
        if (results.length > 0 && delayMs > 0) {
          await new Promise((resolve) => setTimeout(resolve, delayMs));
        }
        const update = await classify(makeState(toRawSubmission(fixture)));
        const actual = update.classification?.category ?? "other";
        const confidence = update.classification?.confidence ?? 0;
        const correct = actual === fixture.expectedCategory;
        results.push({
          id: fixture.id,
          expected: fixture.expectedCategory,
          actual,
          confidence,
          correct,
        });
        expect(TRIAGE_CATEGORIES).toContain(actual);
      }

      const correctCount = results.filter((r) => r.correct).length;
      const accuracy = correctCount / results.length;

      writeEvalReport(results, accuracy);

      console.log(
        `[eval] accuracy ${(accuracy * 100).toFixed(1)}% ` +
          `(${correctCount}/${results.length}) — see EVAL.md`,
      );

      expect(accuracy).toBeGreaterThanOrEqual(0.8);
    },
    900_000,
  );
});

describe.skipIf(enabled)("classification accuracy eval (skipped)", () => {
  it("is skipped — run `npm run eval` to measure accuracy", () => {
    expect(enabled).toBe(false);
  });
});

/** Write EVAL.md — the most recent accuracy report. */
function writeEvalReport(results: Result[], accuracy: number): void {
  const correctCount = results.filter((r) => r.correct).length;

  const perCategory = new Map<string, { total: number; correct: number }>();
  for (const r of results) {
    const bucket = perCategory.get(r.expected) ?? { total: 0, correct: 0 };
    bucket.total += 1;
    if (r.correct) bucket.correct += 1;
    perCategory.set(r.expected, bucket);
  }

  const lines: string[] = [
    "# Classification accuracy — EVAL.md",
    "",
    "Generated by `npm run eval` (`__tests__/agent/accuracy.test.ts`).",
    "",
    `- **Date:** ${new Date().toISOString()}`,
    `- **Model:** ${activeModelId()}`,
    `- **Overall accuracy:** ${(accuracy * 100).toFixed(1)}% (${correctCount}/${results.length})`,
    `- **PRD bar:** ≥ 80% — ${accuracy >= 0.8 ? "PASS" : "FAIL"}`,
    "",
    "## By category",
    "",
    "| Category | Correct | Total |",
    "|----------|---------|-------|",
    ...[...perCategory.entries()].map(
      ([cat, b]) => `| ${cat} | ${b.correct} | ${b.total} |`,
    ),
    "",
    "## Per fixture",
    "",
    "| Fixture | Expected | Actual | Confidence | |",
    "|---------|----------|--------|------------|--|",
    ...results.map(
      (r) =>
        `| ${r.id} | ${r.expected} | ${r.actual} | ${r.confidence} | ${r.correct ? "✓" : "✗"} |`,
    ),
    "",
  ];

  writeFileSync(join(process.cwd(), "EVAL.md"), lines.join("\n"), "utf8");
}
